# Generated by Django 5.2.17 on 2026-09-29 09:54

import apps.listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_backfill_price_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingmedia',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='المدة (ثانية)'),
        ),
        migrations.AddField(
            model_name='listingmedia',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=apps.listings.models.media_path, verbose_name='الفيديو'),
        ),
        migrations.AddField(
            model_name='listingmedia',
            name='video_state',
            field=models.CharField(blank=True, choices=[('', '—'), ('pending', 'بانتظار الضغط'), ('ready', 'مضغوط'), ('failed', 'تعذّر الضغط (يُعرض الأصلي)')], db_index=True, default='', max_length=8, verbose_name='حالة الفيديو'),
        ),
    ]
