# Generated by Django 5.2.17 on 2026-09-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_appconfig_currency_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='max_video_mb',
            field=models.PositiveSmallIntegerField(default=100, help_text='حجم الملف كما يرفعه الجوال، قبل ضغطه على الخادم', verbose_name='أقصى حجم للفيديو (ميغابايت)'),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='max_video_seconds',
            field=models.PositiveSmallIntegerField(default=60, help_text='فيديو واحد لكل إعلان. صفر = إيقاف رفع الفيديو', verbose_name='أقصى مدة للفيديو (ثانية)'),
        ),
        migrations.AlterField(
            model_name='adminlog',
            name='action',
            field=models.CharField(choices=[('approve', 'قبول إعلان'), ('reject', 'رفض إعلان'), ('suspend', 'إيقاف إعلان'), ('delete', 'حذف إعلان'), ('feature', 'تمييز إعلان'), ('user_suspend', 'إيقاف مستخدم'), ('user_ban', 'حظر مستخدم'), ('user_activate', 'تفعيل مستخدم'), ('user_auto_publish', 'تبديل النشر التلقائي'), ('user_password', 'تعيين كلمة مرور لمستخدم'), ('config', 'تعديل الإعدادات'), ('report_resolve', 'معالجة بلاغ'), ('account_deleted', 'حذف حساب بطلب صاحبه')], db_index=True, max_length=24, verbose_name='الإجراء'),
        ),
    ]
