# Generated by Django 5.2.17 on 2026-09-16 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_deletedaccount_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, help_text='ختم يُبطل كل رمز دخول صدر قبله — انظر accounts/tokens.py', null=True, verbose_name='آخر تغيير لكلمة المرور'),
        ),
        migrations.AlterField(
            model_name='user',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='قناة التواصل ووصول رمز استعادة كلمة المرور. يُملأ برقم الحساب تلقائيًا إن تُرك فارغًا (plan3 §3.5)', max_length=20, verbose_name='رقم واتساب'),
        ),
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(db_index=True, max_length=64, verbose_name='بصمة الرمز')),
                ('sent_to', models.CharField(max_length=20, verbose_name='أُرسل إلى')),
                ('channel', models.CharField(default='whatsapp', max_length=16, verbose_name='القناة')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='المحاولات')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='أُنشئ في')),
                ('expires_at', models.DateTimeField(verbose_name='ينتهي في')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='استُهلك في')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_codes', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'رمز استعادة',
                'verbose_name_plural': 'رموز الاستعادة',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'consumed_at'], name='accounts_pa_user_id_4a90a9_idx')],
            },
        ),
    ]
